spring:
  application:
    name: loyalty-rewards-service

  datasource:
    url: jdbc:h2:mem:custpurchasesdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enables: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
